#ifndef __board_common_h
#define __board_common_h

#define BOARD_MOTOR_TYPE_NONE 0
#define BOARD_MOTOR_TYPE_PMSM 1


#define BOARD_MOTOR_CURRENT_SENCE_TYPE_NONE 0
#define BOARD_MOTOR_CURRENT_SENCE_TYPE_ADC 1

#define BOARD_MOTOR_POS_SENCE_TYPE_NONE 0
#define BOARD_MOTOR_POS_SENCE_TYPE_ABS_SSI_32 1


#define BOARD_FREE_MASTER_DRIVER_TYPE_NONE 0
#define BOARD_FREE_MASTER_DRIVER_TYPE_DIRRECT_UART 1
#define BOARD_FREE_MASTER_DRIVER_TYPE_PROTO_SWITCH 2

//Конфигурация и состав привода - его назначение,  подключённые датчик и т.д.
//Для каждой версии привода- свои
#include "board_options.h"

//До определяем  пропущенные опции

#ifndef BOARD_MOTOR_TYPE
#define BOARD_MOTOR_TYPE BOARD_MOTOR_TYPE_NONE
#endif

#ifndef BOARD_MOTOR_CURRENT_SENCE_TYPE
#define BOARD_MOTOR_CURRENT_SENCE_TYPE BOARD_MOTOR_CURRENT_SENCE_TYPE_NONE
#endif 

#ifndef BOARD_MOTOR_POS_SENCE_TYPE 
#define BOARD_MOTOR_POS_SENCE_TYPE MOTOR_POS_SENCE_TYPE_NONE
#endif

#ifndef BOARD_ACTUATOR_POS_SENCE_TYPE 
#define BOARD_ACTUATOR_POS_SENCE_TYPE ACTUATOR_POS_SENCE_TYPE_NONE
#endif

#ifndef BOARD_MEXO_NET_FLOW_ENABLED
#define BOARD_MEXO_NET_FLOW_ENABLED 0
#endif

#ifndef BOARD_TERMINAL_ENABLED
#define BOARD_TERMINAL_ENABLED 0
#endif

#ifndef BOARD_NET_PROTO_SWITCH_ENABLED
#define BOARD_NET_PROTO_SWITCH_ENABLED 0
#endif

#ifndef BOARD_FREE_MASTER_DRIVER_TYPE
#define BOARD_FREE_MASTER_DRIVER_TYPE BOARD_FREE_MASTER_DRIVER_TYPE_NONE
#endif 

#if BOARD_FREE_MASTER_DRIVER_TYPE == BOARD_FREE_MASTER_DRIVER_TYPE_NONE
#define BOARD_FREEMASTER_ENABLED 0
#define MEXO_FREEMASTER_ENABLED 0
#else
#define BOARD_FREEMASTER_ENABLED 1
#define MEXO_FREEMASTER_ENABLED 1
#endif

#if BOARD_MOTOR_TYPE == BOARD_MOTOR_TYPE_NONE
#define BOARD_MOTOR_ENABLED 0
#define BOARD_MOTOR_CURRENT_SENCE_ENABLED 0
#define BOARD_MOTOR_POS_SENCE_ENABLED 0
#else
#define BOARD_MOTOR_ENABLED 1
#if BOARD_MOTOR_CURRENT_SENCE_TYPE == BOARD_MOTOR_CURRENT_SENCE_TYPE_NONE
#define BOARD_MOTOR_CURRENT_SENCE_ENABLED 0
#else
#define BOARD_MOTOR_CURRENT_SENCE_ENABLED 1
#endif 

#if BOARD_MOTOR_POS_SENCE_TYPE == BOARD_MOTOR_POS_SENCE_TYPE_NONE
#define BOARD_MOTOR_POS_SENCE_ENABLED 0
#else
#define BOARD_MOTOR_POS_SENCE_ENABLED 1
#endif 

#endif 

#ifndef BOARD_STARTUP_PAUSE_US
#define BOARD_STARTUP_PAUSE_US 100000
#endif

#define BOARD_TICK_PERIOD_US ((BOARD_TICK_PERIOD_NS+500)/1000)

#endif
